name: Translate README

on:
  workflow_dispatch:

jobs:
  translate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Language Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - French
        uses: dephraiim/translate-readme@v1
        with:
          LANG: fr
      - name: Adding README - Spanish
        uses: dephraiim/translate-readme@v1
        with:
          LANG: es
      - name: Adding README - German
        uses: dephraiim/translate-readme@v1
        with:
          LANG: de
      - name: Adding README - Japanese
        uses: dephraiim/translate-readme@v1
        with:
          LANG: ja
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@v1
        with:
          LANG: zh-CN
      - name: Adding README - Russian
        uses: dephraiim/translate-readme@v1
        with:
          LANG: ru
